name: auto-signin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Setup Chrome & chromedriver
        uses: browser-actions/setup-chrome@v1
      - name: Install chromedriver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Working
        run: |
          python ./jlc.py ${{ secrets.JLC_USERNAME }} ${{ secrets.JLC_PASSWORD }}
